version: '3.5'
services:
  dst-server:
    platform: linux/arm64/v8
    image: jamesits/dst-server:latest
    restart: always
    ports:
      - "10999-11000:10999-11000/udp"
      - "12346-12347:12346-12347/udp"
    volumes:
      - ./data:/data
    stop_grace_period: 6m